# ??????
spring:
  profiles:
    active: @profiles.active@
  mvc:
    throw-exception-if-no-handler-found: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl